config/routes.rb
Rails.application.routes.draw do

  root to: 'links#new'

  resources :links
  get '/most_visited_pages' => 'links#most_visited_pages', as: :most_visited_pages
  get '/:shortlink' => 'links#render_original_url', as: :short_link

end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :link, uniqueness: true, presence: true
	validates :shortlink, uniqueness: true, presence: true

	def generate_short_link(characters)
		chain = gen_random_chain(characters)
		
		while (Link.find_by shortlink: chain) do
			binding.pry
			chain = gen_random_chain(characters)
		end

		self.shortlink = chain
	end

	def gen_random_chain(characters)
		chain =""
		characters.times do |n|
			character = rand(48..122)
			character = rand(48..122) while (58..64).include?(character) || (91..97).include?(character)
			chain << character.chr
		end
		chain
	end

	def update_visits
		self.visits += 1
    	self.last_visit = Date.today
    	self.save
	end

	def add_http
		if !self.link.start_with?("http://")
			self.link.prepend("http://") 
			self.save 
		end
	end

	def self.find_or_create_link(permited_params)
		future_link = Link.find_with_http(permited_params)
		if !future_link
			new_link = Link.new(permited_params)
			new_link.generate_short_link(3)
			new_link.save
			new_link
		else
			future_link
		end
	end

	def self.find_with_http(params)
		original_link = params[:link]
   		original_link.prepend("http://") if !original_link.start_with?("http://") && !original_link.empty?

   		link = Link.find_by link: original_link

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find params[:id]
  end

  def new
  	@link = Link.new
  end

  def edit

  end

  def create	
    @link = Link.find_or_create_link(permited_params)
    if @link.valid?
      redirect_to link_path(@link)
    else
      render 'new'
    end
  end

  def render_original_url
    @link = Link.find_by shortlink: params[:shortlink]
    @link.update_visits
    redirect_to @link.link
  end

  def most_visited_pages
    @most_visited_pages = Link.order(visits: :desc).limit(10) 
  end

  private

  def permited_params
    params.require(:link).permit(:link, :shortlink)   
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  
    <%= f.label :link %><br>
    <%= f.text_field :link %>

    <%= f.submit %>
<% end %>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/index.html.erb
<h1>All the links</h1>

<ul>
	<% @links.each do |link| %>
		<li>
			<%= link_to(link.link, link_path(link)) + " / created on " + link.created_at.to_date.to_s + " / visited " + link.visits.to_s + " times" %>
		</li>

	<% end %>

</ul>

app/views/links/most_visited_pages.html.erb
<h1>10 Most visited pages</h1>


<ol>
	<% @most_visited_pages.each do |link| %>
		<li><%= link_to link.link, link_path(link)%></li>
	<% end %>

</ol>

app/views/links/new.html.erb
<h1>Enter your url</h1>

<%= render 'form' %>

<p>See the <%= link_to "most visited pages", most_visited_pages_path%>, or the list of <%= link_to "all links", links_path %> in the app</p>

app/views/links/show.html.erb
<h1>Here is your link</h1>

<p><%= link_to "http://localhost:3000/#{@link.shortlink}", short_link_path(@link.shortlink)  %> </p>

app/views/site/home.html.erb
<h1>Site#home</h1>
<p>Find me in app/views/site/home.html.erb</p>